### ISSUE TITLE
好像需要更新至Android x

### ISSUE THREAD

**Issue by k3v1n-uncle** [JackZhang1994/flutter_step_count#1]

**Comment by JackZhang1994** [comment]
最近有点忙，可能顾不上这了个。如果比较着急，可以fork下来自己修改下~  Sry~

**Comment by k3v1n-uncle** [comment]
好的

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: JackZhang1994 <notifications@github.com>
发送时间: Wednesday, February 26, 2020 6:07:26 PM
收件人: JackZhang1994/flutter_step_count <flutter_step_count@noreply.github.com>
抄送: xuwankang <xuxiaobao1992@live.com>; Author <author@noreply.github.com>
主题: Re: [JackZhang1994/flutter_step_count] 好像需要更新至Android x (#1)


最近有点忙，可能顾不上这了个。如果比较着急，可以fork下来自己修改下~ Sry~

―
